# Nama workflow yang akan tampil di tab Actions GitHub
name: Build SukiSU and Notify Telegram

# Pemicu workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_notify:
    # Menggunakan sistem operasi Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
      # LANGKAH 1: Mengunduh (Checkout) Kode dari Repositori ASLI SukiSU
      # Ini adalah perbaikan penting untuk memastikan semua file proyek terunduh.
      - name: Checkout SukiSU-Ultra repository
        uses: actions/checkout@v4
        with:
          repository: 'SukiSU-Ultra/SukiSU'
          ref: 'main'
          fetch-depth: 0

      # LANGKAH 2: [DEBUG] Verifikasi File Setelah Checkout
      # Langkah ini WAJIB ADA. Jika tidak muncul, berarti file ini belum dijalankan.
      - name: '[DEBUG] List files in the root directory'
        run: ls -la

      # LANGKAH 3: Menyiapkan Lingkungan Build Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Menggunakan cache untuk dependensi Gradle
      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      # LANGKAH 4: Memberikan Izin Eksekusi pada Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # LANGKAH 5: Membangun Proyek dan Membuat APK
      - name: Build with Gradle
        run: ./gradlew :app:assembleRelease

      # LANGKAH 6: [DEBUG] Verifikasi Hasil Build APK
      - name: '[DEBUG] List contents of APK output directory'
        run: ls -R app/build/outputs/apk/release

      # LANGKAH 7: Mengambil Changelog dari Commit Terakhir
      - name: Get Commit Changelog
        id: changelog
        run: echo "changelog_message<<EOF$(git log -1 --pretty=%B)EOF" >> $GITHUB_OUTPUT

      # LANGKAH 8: Mengirim APK dan Notifikasi ke Telegram
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: app/build/outputs/apk/release/app-release.apk
          message: |
            *🚀 New SukiSU Build is Ready!*
            *Version:* `SukiSU_v1.0_build-${{ github.run_number }}`
            *Commit by:* `${{ github.actor }}`
            *Branch:* `${{ github.ref_name }}`
            *Changelog:*
            ```
            ${{ steps.changelog.outputs.changelog_message }}
            ```

