# Nama workflow yang akan tampil di tab Actions GitHub
name: Build and Notify Telegram

# Pemicu workflow: dijalankan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ main ] # Ganti 'main' jika nama branch utama Anda berbeda (mis: 'master')

jobs:
  build_and_notify:
    # Menggunakan runner Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 'fetch-depth: 0' diperlukan untuk mengambil semua riwayat git,
        # agar kita bisa membuat changelog dari commit sebelumnya.
        fetch-depth: 0

    # =========================================================================
    # == Sesuaikan bagian ini dengan langkah-langkah build proyek Anda ==
    # =========================================================================
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # Menjalankan build untuk debug dan release sekaligus.
    - name: Build Debug and Release APKs
      run: ./gradlew assembleDebug assembleRelease
      continue-on-error: true
    # =========================================================================
    # == Akhir dari bagian yang perlu disesuaikan ==
    # =========================================================================

    # Langkah 2 (Diperbaiki): Buat Changelog secara dinamis
    - name: Generate Changelog
      id: generate_changelog
      run: |
        # Ambil daftar log commit. Ini bisa kosong jika ini adalah push pertama atau force-push.
        COMMIT_LOGS=$(git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"- %s")
        
        # Cek apakah variabel COMMIT_LOGS berisi teks (ada commit baru)
        if [ -n "$COMMIT_LOGS" ]; then
          # Jika ada, buat konten changelog dengan header
          CHANGELOG_TEXT="📝 **Changelog:**\n$COMMIT_LOGS"
        else
          # Jika tidak ada, biarkan konten kosong
          CHANGELOG_TEXT=""
        fi
        
        # Menyimpan string (bisa multiline) ke environment variable GitHub
        # Ini adalah cara yang aman untuk menangani string yang mungkin berisi karakter khusus
        {
          echo 'CHANGELOG_CONTENT<<EOF'
          echo "$CHANGELOG_TEXT"
          echo 'EOF'
        } >> "$GITHUB_ENV"

    # Langkah 3: Cari file .apk yang telah di-build
    - name: Find APK files
      id: find_files
      run: |
        DEBUG_APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
        RELEASE_APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
        
        echo "DEBUG_APK_PATH=$DEBUG_APK_PATH" >> $GITHUB_ENV
        echo "RELEASE_APK_PATH=$RELEASE_APK_PATH" >> $GITHUB_ENV
        
        echo "debug_apk_found=$(if [ -f "$DEBUG_APK_PATH" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT
        echo "release_apk_found=$(if [ -f "$RELEASE_APK_PATH" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT
        
        echo "Debug APK Found: $(if [ -f "$DEBUG_APK_PATH" ]; then echo "Yes"; else echo "No"; fi)"
        echo "Release APK Found: $(if [ -f "$RELEASE_APK_PATH" ]; then echo "Yes"; else echo "No"; fi)"
        
    # Langkah 4: Kirim build DEBUG jika ada
    - name: Send Debug APK to Telegram
      if: steps.find_files.outputs.debug_apk_found == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        document: ${{ env.DEBUG_APK_PATH }}
        caption: |
          🎉 **Build DEBUG Baru Tersedia!** 🎉

          **Repository:** `${{ github.repository }}`
          
          **Revisi:**
          - **Commit:** `[Lihat Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})`
          - **Workflow Run:** `[Lihat Laporan Build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
          
          ${{ env.CHANGELOG_CONTENT }}
        format: markdown

    # Langkah 5: Kirim build RELEASE jika ada
    - name: Send Release APK to Telegram
      if: steps.find_files.outputs.release_apk_found == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        document: ${{ env.RELEASE_APK_PATH }}
        caption: |
          🚀 **Build RELEASE Baru Tersedia!** 🚀

          **Repository:** `${{ github.repository }}`
          
          **Revisi:**
          - **Commit:** `[Lihat Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})`
          - **Workflow Run:** `[Lihat Laporan Build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`

          ${{ env.CHANGELOG_CONTENT }}
        format: markdown
