# Nama workflow yang akan tampil di tab Actions GitHub
name: Build SukiSU and Notify Telegram

# Pemicu workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_notify:
    # Menggunakan sistem operasi Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
      # LANGKAH 1: Mengunduh (Checkout) Kode dari Repositori Fork Anda
      - name: Checkout Your Fork's Repository
        uses: actions/checkout@v4
        with:
          # Memberikan izin pada workflow untuk melakukan push (dibutuhkan untuk git pull)
          token: ${{ secrets.GITHUB_TOKEN }}

      # LANGKAH 2: [PERBAIKAN] Sinkronisasi Otomatis dengan Repositori Asli
      # Ini akan memastikan kode Anda selalu yang paling baru sebelum di-build.
      - name: Sync with Original (Upstream) Repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote add upstream https://github.com/SukiSU-Ultra/SukiSU.git
          git fetch upstream
          git reset --hard upstream/main

      # LANGKAH 3: Menyiapkan Lingkungan Build Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # LANGKAH 4: Memberikan Izin Eksekusi pada Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # LANGKAH 5: Membangun Proyek dan Membuat APK
      - name: Build with Gradle
        run: ./gradlew :app:assembleRelease

      # LANGKAH 6: [FITUR BARU] Menemukan File APK & Menetapkan Nama Dinamis
      # Secara otomatis mencari file .apk di folder output.
      - name: Find APK File and Set Dynamic Name
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -type f -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "apk_filename=$(basename $APK_PATH)" >> $GITHUB_OUTPUT

      # LANGKAH 7: Mengambil Changelog dari Commit Terakhir
      - name: Get Commit Changelog
        id: changelog
        run: echo "changelog_message<<EOF$(git log -1 --pretty=%B)EOF" >> $GITHUB_OUTPUT

      # LANGKAH 8: Mengirim APK dan Notifikasi ke Telegram
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # Menggunakan path APK yang ditemukan secara dinamis dari langkah #6
          document: ${{ steps.find_apk.outputs.apk_path }}
          message: |
            *🚀 New SukiSU Build is Ready!*

            *File:* `${{ steps.find_apk.outputs.apk_filename }}`
            *Build:* `${{ github.run_number }}`
            *Branch:* `${{ github.ref_name }}`

            *Changelog:*
            ```
            ${{ steps.changelog.outputs.changelog_message }}
            ```

